// import basilBottle from './assets/images/basil-bottle.webp';
// import lemonBottle from './assets/images/lemon-bottle.webp';
// import garlicBottle from './assets/images/garlic-bottle.webp';
// import rosemaryBottle from './assets/images/rosemary-bottle.webp';
// import chiliBottle from './assets/images/chili-bottle.webp';
// import delicateBottle from './assets/images/delicate-bottle.webp';
// import mediumBottle from './assets/images/medium-bottle.webp';
// import boldBottle from './assets/images/bold-bottle.webp';
export const cartItems = ['123','234','345'];
